### ISSUE TITLE
Is data for this analysis publicly available?

### ISSUE THREAD

**Issue by ftlbiped** [blab/ncov-severity#1]
This is a lovely piece of analysis, but it looks like the data it is based on are not included with or linked to from the repo. Is your viral sequencing and qPCR data taken from a publicly available source, or is it an as-yet unpublished in-house result? Is this repo shared on Github in lieu of or in tandem with a BioRxiv preprint, or in advance of an upcoming publication in which non-PII data will be released?

**Comment by cassiawag** [comment]
Hi @dkassler, sorry for the delay in response. I missed seeing this! A publication is forthcoming shortly -- this repo was a first step in the analysis, and the data (without PII) is now available under `data`.
